# =============================================================================
# HORIZONTAL POD AUTOSCALER (HPA): myapp
# Automatically scales pods based on CPU and memory usage.
# Requires: Metrics Server (12-metrics-server.tf) to be installed.
# When nodes run out of resources, Cluster Autoscaler (14-cluster-autoscaler.tf)
# adds more EC2 instances to accommodate new pods.
# =============================================================================
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
  namespace: 3-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp                   # The deployment to scale
  minReplicas: 1                  # Minimum pods (even at zero traffic)
  maxReplicas: 3                  # Maximum pods (cost control)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Scale up when CPU > 80% average
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # Scale up when memory > 70% average