# =============================================================================
# SERVICE ACCOUNT: myapp-sa
# This serves as the "Passport" for our pods.
# It is mapped to the "secrets-csi" IAM role in 21-secrets-store-csi-driver.tf
# via EKS Pod Identity.
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: 12-example
