# =============================================================================
# SECRET PROVIDER CLASS: aws-secrets
# This tells the CSI driver exactly WHICH AWS secrets to fetch and HOW
# to present them as files in the pod.
#
# Use case: fetching "MyTestSecret" from AWS Secrets Manager.
# =============================================================================
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: 12-example
spec:
  provider: aws
  parameters:
    region: "eu-west-1"
    usePodIdentity: "true"  # Use EKS Pod Identity instead of IRSA
    objects: |
      - objectName: "MyTestSecret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "api_key"    # The key inside the JSON secret
            objectAlias: "api_key" # The name of the file created in the pod
      
      - objectName: "prod/k8s/credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"   # → /mnt/secrets-store/db_username = "Muhirwa"
          - path: "password"
            objectAlias: "db_password"   # → /mnt/secrets-store/db_password = "Typeshit"

